---
- hosts: trk 
  remote_user: root
  tasks:
  - name: install devel
    yum: 
      name: "{{item}}"
      state: installed
    with_items:
    - gcc
    - gcc-c++
    - make
    - cmake
    - automake
    - autoconf
    - unzip
    - iptables-services
  - name: make directory
    shell: mkdir -p /usr/local/src  /data/pkgs  /fastdfs/tracker
  - name: copy tarball,copy zip
    copy: 
      src: /root/ansible/pkgs/fastdfs
      dest: /data/pkgs
  - name: tar , unzip
    shell: cd /data/pkgs/fastdfs && tar -xf FastDFS_v5.08.tar.gz -C /usr/local/src/ && unzip libfastcommon-master.zip -d /usr/local/src/ 
  - name: make libfastcommon-master
    shell: cd /usr/local/src/libfastcommon-master && ./make.sh && ./make.sh install
  - name: make FastDFS
    shell: cd /usr/local/src/FastDFS && ./make.sh && ./make.sh install
    
  - name: conf tracker
    shell: cp /etc/fdfs/tracker.conf.sample /etc/fdfs/tracker.conf
  - name: conf tracker
    lineinfile:
      path: /etc/fdfs/tracker.conf 
      regexp: "^disabled="
      line: "disabled=false"
  - name: conf tracker
    lineinfile:
      path: /etc/fdfs/tracker.conf
      regexp: "^port="
      line: "port=22122"
  - name: conf tracker
    lineinfile:
      path: /etc/fdfs/tracker.conf
      regexp: "^base_path="
      line: "base_path=/fastdfs/tracker"
  - name: conf tracker
    lineinfile:
      path: /etc/fdfs/tracker.conf
      regexp: "^storage_group="
      line: "storage_group=group1"
  - name: start tracker
    shell: /etc/init.d/fdfs_trackerd start && netstat -untlp | grep :22122
    tags: start
