---
- hosts: sto
  remote_user: root
  vars:
    tracker1: 192.168.1.11
    tracker2: 192.168.1.12
  tasks:
  - name: install devel
    yum: 
      name: "{{item}}"
      state: installed
    with_items:
    - gcc
    - gcc-c++
    - make
    - cmake
    - automake
    - autoconf
    - unzip
    - iptables-services
    - openssl
    - openssl-devel
    - zlib
    
  - name: make directory
    shell: mkdir -p /usr/local/src  /data/pkgs  /fastdfs/storage
  - name: copy tarball,copy zip
    copy: 
      src: /root/git/sh/ansible/fastdfs/pkgs/fastdfs
      dest: /data/pkgs
  - name: tar , unzip
    shell: cd /data/pkgs/fastdfs && tar -xf FastDFS_v5.08.tar.gz -C /usr/local/src/ && unzip libfastcommon-master.zip -d /usr/local/src/ 
  - name: make libfastcommon-master
    shell: cd /usr/local/src/libfastcommon-master && ./make.sh && ./make.sh install
  - name: make FastDFS
    shell: cd /usr/local/src/FastDFS && ./make.sh && ./make.sh install
    
  - name: conf storage
    shell: cp /etc/fdfs/storage.conf.sample /etc/fdfs/storage.conf
  - name: conf storage
    lineinfile:
      path: /etc/fdfs/storage.conf 
      regexp: "^disabled="
      line: "disabled=false"
  - name: conf storage
    lineinfile:
      path: /etc/fdfs/storage.conf
      regexp: "^port="
      line: "port=23000"
  - name: conf storage
    lineinfile:
      path: /etc/fdfs/storage.conf
      regexp: "^base_path="
      line: "base_path=/fastdfs/storage"
  - name: conf storage
    lineinfile:
      path: /etc/fdfs/storage.conf
      regexp: "^store_path0"
      line: "store_path0=/fastdfs/storage"
  - name: conf storage_tracker1
    lineinfile:
      path: /etc/fdfs/storage.conf
      regexp: "^tracker_server"
      line: 'tracker_server={{tracker1}}:22122'
  - name: conf storage_tracker2
    lineinfile:
      dest: /etc/fdfs/storage.conf
      regexp: "^cker_sercer="
      insertafter: '^tracker_sercer={{tracker1}}:22122'
      line: "{{item.line}}"
    with_items:
    - { line: 'tracker_server={{tracker2}}:22122'}
  - name: conf storage_tracker1
    lineinfile:
      path: /etc/fdfs/storage.conf
      regexp: '^http.server_port'
      line: "http.server_port=8888"
  - name: conf iptables
    lineinfile:
      dest: /etc/sysconfig/iptables
      regexp: "^filter"
      insertbefore: "^COMMIT"
      line: "{{item.line}}"
    with_items:
    - { line: '-A INPUT -m state --state NEW -p tcp --dport 23000 -j ACCEPT'}
    tags: iptables
  - name: daemon reload
    shell: systemctl daemon-reload
  - name: restart iptables
    service: 
      name: iptables
      state: restarted
    tags: iptables
  - name: start storage
    shell: /etc/init.d/fdfs_storaged start 
    tags: start
