---
- hosts: trk
  remote_user: root
  tasks:
  - name: conf iptables
    lineinfile:
      dest: /etc/sysconfig/iptables
      regexp: "^filter"
      insertbefore: "^COMMIT"
      line: "{{item.line}}"
    with_items:
    - { line: '-A INPUT -m state --state NEW -p tcp --dport 22122 -j ACCEPT'}

