---
- hosts: db
  remote_user: root
  vars:
    pkg_dir: /data/pkgs
    script_path: /root/git/sh/NFDW_mysql_install.sh
  tasks: 
    - name: create pkgs dir
      shell: if [ ! -d "{{pkg_dir }}" ]; then mkdir -p "{{pkg_dir}}"; fi
    - name: install mysql
      script: /root/git/sh/NFDW_mysql_install.sh  "{{pkg_dir}}/mysql"
