# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webansi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ipaddr',
            field=models.CharField(max_length=15),
        ),
    ]
